#!/bin/bash
#
# Start the Hyperscale monitoring stack (Prometheus + Grafana) for a distributed cluster
#
# Usage:
#   ./scripts/monitoring/distributed-monitoring.sh --nodes "IP1,IP2..." [--port PORT]
#
# Example:
#   ./scripts/monitoring/distributed-monitoring.sh --nodes "192.168.1.10,192.168.1.11"
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Default
NODES=""
RPC_PORT=8080

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --nodes)
            NODES="$2"
            shift 2
            ;;
        --port)
            RPC_PORT="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 --nodes \"IP1,IP2...\" [--port PORT]"
            echo ""
            echo "Options:"
            echo "  --nodes LIST     Comma-separated list of node IPs"
            echo "  --port PORT      RPC port (default: 8080)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "$NODES" ]; then
    echo "ERROR: --nodes argument is required (comma-separated IPs)"
    echo "Usage: $0 --nodes \"192.168.1.10,192.168.1.11\""
    exit 1
fi

echo "=== Starting Monitoring Stack (Distributed) ==="
echo "Nodes: $NODES"
echo "RPC Port: $RPC_PORT"
echo ""

# Split nodes into array
IFS=',' read -r -a NODE_IPS <<< "$NODES"

# Build targets list for Prometheus using standard array syntax
PROM_TARGETS=""
for i in "${!NODE_IPS[@]}"; do
    IP="${NODE_IPS[$i]}"
    TRIMMED_IP=$(echo "$IP" | xargs)
    if [ -n "$PROM_TARGETS" ]; then
        PROM_TARGETS="$PROM_TARGETS, "
    fi
    PROM_TARGETS="$PROM_TARGETS'$TRIMMED_IP:$RPC_PORT'"
done

echo "Generating Prometheus configuration..."
cat > "$SCRIPT_DIR/prometheus.yml" << EOF
# Prometheus configuration for Hyperscale distributed cluster
# Auto-generated by distributed-monitoring.sh

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hyperscale-distributed'
    scrape_interval: 5s
    static_configs:
      - targets: [$PROM_TARGETS]
        labels:
          cluster: 'distributed'
EOF

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker not found. Please install Docker first."
    exit 1
fi

DC=$(command -v docker-compose >/dev/null 2>&1 && echo "docker-compose" || echo "docker compose")

# Start containers
echo "Starting Prometheus and Grafana..."
$DC up -d

echo ""
echo "=== Monitoring Stack Started ==="
echo ""
echo "Access:"
echo "  Prometheus: http://localhost:9090"
echo "  Grafana:    http://localhost:3000 (admin/admin)"
echo ""
echo "Configuration written to $SCRIPT_DIR/prometheus.yml"
echo "Targets: [$PROM_TARGETS]"
