#!/bin/bash
#
# Start the Hyperscale monitoring stack (Prometheus + Grafana) for a distributed cluster
#
# Usage:
#   ./scripts/monitoring/start-distributed-monitoring.sh --targets "IP1:PORT1,IP2:PORT2..."
#
# Example:
#   ./scripts/monitoring/start-distributed-monitoring.sh --targets "192.168.1.10:8080,192.168.1.10:8081"
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Default
TARGETS=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --targets)
            TARGETS="$2"
            shift 2
            ;;
        --nodes) # Backwards compatibility/alias
            TARGETS="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 --targets \"IP1:PORT1,IP2:PORT2...\""
            echo ""
            echo "Options:"
            echo "  --targets LIST   Comma-separated list of targets (host:port)"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [ -z "$TARGETS" ]; then
    echo "ERROR: --targets argument is required (comma-separated host:port list)"
    echo "Usage: $0 --targets \"192.168.1.10:8080,192.168.1.10:8081\""
    exit 1
fi

echo "=== Starting Monitoring Stack (Distributed) ==="
echo "Targets: $TARGETS"
echo ""

# Split targets into array
IFS=',' read -r -a TARGET_LIST <<< "$TARGETS"

# Build targets list for Prometheus using standard array syntax
PROM_TARGETS=""
for i in "${!TARGET_LIST[@]}"; do
    TARGET="${TARGET_LIST[$i]}"
    TRIMMED_TARGET=$(echo "$TARGET" | xargs)
    if [ -n "$PROM_TARGETS" ]; then
        PROM_TARGETS="$PROM_TARGETS, "
    fi
    # Assume the target is already in host:port format
    PROM_TARGETS="$PROM_TARGETS'$TRIMMED_TARGET'"
done

echo "Generating Prometheus configuration..."
cat > "$SCRIPT_DIR/prometheus.yml" << EOF
# Prometheus configuration for Hyperscale distributed cluster
# Auto-generated by start-distributed-monitoring.sh

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hyperscale'
    scrape_interval: 5s
    static_configs:
      - targets: [$PROM_TARGETS]
        labels:
          cluster: 'distributed'
          shard: '0'
EOF

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "ERROR: Docker not found. Please install Docker first."
    exit 1
fi

DC=$(command -v docker-compose >/dev/null 2>&1 && echo "docker-compose" || echo "docker compose")

# Start containers
echo "Starting Prometheus and Grafana..."

# MacOS and Linux need different settings
COMPOSE_FLAGS=""
if [[ "$(uname -s)" == "Linux" ]]; then
    echo "Detected Linux: Adding extra_hosts configuration..."
    COMPOSE_FLAGS="-f docker-compose.yml -f docker-compose.linux.yml"
fi

$DC $COMPOSE_FLAGS up -d --force-recreate

echo ""
echo "=== Monitoring Stack Started ==="
echo ""
echo "Access:"
echo "  Prometheus: http://localhost:9090"
echo "  Grafana:    http://localhost:3000 (admin/admin)"
echo ""
echo "Configuration written to $SCRIPT_DIR/prometheus.yml"
echo "Targets: [$PROM_TARGETS]"
