//! Unified I/O loop for action processing.
//!
//! `IoLoop` handles ALL actions from `NodeStateMachine`, dispatching them via
//! generic trait methods (Network, Dispatch, Storage) and concrete types for
//! timer ops and event delivery. Both production and simulation runners construct
//! an `IoLoop` with their concrete trait implementations.
//!
//! # Driving modes
//!
//! - **Production**: `IoLoop::run()` blocks on a crossbeam channel, processing
//!   events as they arrive from tokio bridge tasks.
//! - **Simulation**: The harness calls `IoLoop::step()` per event, then drains
//!   buffered outputs (timer ops, events, sync I/O).
//!
//! # Batching
//!
//! IoLoop batches execution-layer broadcasts and crypto verification for
//! efficiency. Batch deadlines are tracked as logical time (`Duration`) so both
//! production (wall clock) and simulation (logical clock) use the same paths.

use crate::action_handler::{self, ActionContext, DispatchPool};
use crate::batch_accumulator::{BatchAccumulator, ShardedBatchAccumulator};
use crate::config::NodeConfig;
use crate::protocol::fetch::{FetchInput, FetchKind, FetchOutput, FetchProtocol};
use crate::protocol::provision_fetch::{
    ProvisionFetchInput, ProvisionFetchOutput, ProvisionFetchProtocol,
};
use crate::protocol::sync::{SyncInput, SyncOutput, SyncProtocol, SyncStatus};
use crate::NodeStateMachine;
use hyperscale_core::{
    Action, CrossShardExecutionRequest, NodeInput, ProtocolEvent, StateMachine, TimerId,
};
use hyperscale_dispatch::Dispatch;
use hyperscale_engine::{RadixExecutor, TransactionValidation};
use hyperscale_messages::{
    BlockHeaderNotification, BlockVoteNotification, ExecutionCertificatesNotification,
    ExecutionVotesNotification, TransactionCertificateNotification, TransactionGossip,
};
use hyperscale_metrics as metrics;
use hyperscale_network::Network;
use hyperscale_storage::{CommitStore, ConsensusStore, SubstateStore};
use hyperscale_types::{
    Bls12381G1PrivateKey, Bls12381G1PublicKey, CommittedBlockHeader, ExecutionCertificate,
    ExecutionVote, Hash, RoutableTransaction, ShardGroupId, Topology, TransactionCertificate,
    ValidatorId,
};
use quick_cache::sync::Cache as QuickCache;
use std::collections::{HashMap, HashSet};
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tracing::{debug, trace, warn};

/// Default certificate cache capacity.
const DEFAULT_CERT_CACHE_SIZE: usize = 10_000;
/// Default transaction cache capacity.
const DEFAULT_TX_CACHE_SIZE: usize = 50_000;
/// Default transaction status cache capacity.
const DEFAULT_TX_STATUS_CACHE_SIZE: usize = 100_000;
/// Maximum age for pending certificate verifications before cleanup.
const PENDING_CERT_VERIFICATION_TIMEOUT: Duration = Duration::from_secs(30);

/// Pending verification of a received TransactionCertificate.
///
/// When we receive a TransactionCertificate, we verify each embedded
/// ExecutionCertificate's BLS signature before persisting. This tracks the verification
/// progress for a single certificate.
struct PendingCertificateVerification {
    /// The certificate being verified.
    certificate: Arc<TransactionCertificate>,
    /// Shards still awaiting verification callback.
    pending_shards: HashSet<ShardGroupId>,
    /// Whether any verification has failed.
    failed: bool,
    /// When this verification started (logical time from state.now()).
    created_at: Duration,
}

use hyperscale_execution::handlers::UnverifiedExecutionVote;

/// A single execution-vote verification item: tx_hash with its unverified votes.
type ExecutionVoteVerificationItem = (Hash, Vec<UnverifiedExecutionVote>);

/// A committed header pending sender-signature verification.
type CommittedHeaderVerificationItem = (
    CommittedBlockHeader,
    ValidatorId,
    Bls12381G1PublicKey,
    hyperscale_types::Bls12381G2Signature,
);

// ═══════════════════════════════════════════════════════════════════════
// TimerOp — buffered timer operations for the runner
// ═══════════════════════════════════════════════════════════════════════

/// A timer operation buffered by IoLoop for the runner to process.
#[derive(Debug, Clone)]
pub enum TimerOp {
    /// Set a timer to fire after `duration`.
    Set { id: TimerId, duration: Duration },
    /// Cancel a previously set timer.
    Cancel { id: TimerId },
}

// ═══════════════════════════════════════════════════════════════════════
// StepOutput — returned to the caller after processing an event
// ═══════════════════════════════════════════════════════════════════════

/// Output from processing a single event via `IoLoop::step()`.
///
/// IoLoop now handles all sync/fetch I/O internally via the Network trait.
/// The runner processes emitted transaction statuses and timer operations.
pub struct StepOutput {
    /// Transaction status notifications emitted during this step.
    pub emitted_statuses: Vec<(Hash, hyperscale_types::TransactionStatus)>,
    /// Number of actions generated by the state machine during this step.
    pub actions_generated: usize,
    /// Timer operations (set/cancel) to be processed by the runner.
    pub timer_ops: Vec<TimerOp>,
}

// ═══════════════════════════════════════════════════════════════════════
// NodeStatusSnapshot — periodic status for external APIs
// ═══════════════════════════════════════════════════════════════════════

/// Snapshot of node state for external status APIs.
///
/// Produced by [`IoLoop::status_snapshot()`] on the periodic metrics tick.
/// The production runner maps this into its RPC shared state types.
#[derive(Debug, Clone)]
pub struct NodeStatusSnapshot {
    pub committed_height: u64,
    pub view: u64,
    pub state_version: u64,
    pub state_root: Hash,
    pub sync: SyncStatus,
    pub mempool_pending: usize,
    /// Block committed, being executed.
    pub mempool_committed: usize,
    /// Execution done, awaiting certificate.
    pub mempool_executed: usize,
    pub mempool_total: usize,
    /// Waiting for winner.
    pub mempool_deferred: usize,
    pub accepting_rpc_transactions: bool,
    pub at_pending_limit: bool,
}

// ═══════════════════════════════════════════════════════════════════════
// IoLoop
// ═══════════════════════════════════════════════════════════════════════

/// Unified I/O loop that processes all actions from the state machine.
///
/// Generic over:
/// - `S`: Storage (CommitStore + SubstateStore + ConsensusStore)
/// - `N`: Network (message sending)
/// - `D`: Dispatch (thread pool work scheduling)
pub struct IoLoop<S, N, D>
where
    S: CommitStore + SubstateStore + ConsensusStore,
    D: Dispatch,
{
    // Core components
    state: NodeStateMachine,
    storage: Arc<S>,
    executor: RadixExecutor,
    network: N,
    dispatch: D,
    event_sender: crossbeam::channel::Sender<NodeInput>,

    // Identity
    signing_key: Arc<Bls12381G1PrivateKey>,
    topology: Arc<dyn Topology>,
    local_shard: ShardGroupId,
    validator_id: ValidatorId,

    // Prepared commit cache (shared with dispatch closures)
    prepared_commits: Arc<Mutex<HashMap<Hash, S::PreparedCommit>>>,

    // In-memory caches (shared with inbound router in production)
    cert_cache: Arc<QuickCache<Hash, Arc<TransactionCertificate>>>,
    tx_cache: Arc<QuickCache<Hash, Arc<RoutableTransaction>>>,

    // Certificate verification tracking
    pending_cert_verifications: HashMap<Hash, PendingCertificateVerification>,

    // Sync protocol
    sync_protocol: SyncProtocol,

    // Fetch protocol (transaction/certificate fetching with chunking and retry)
    fetch_protocol: FetchProtocol,

    // Provision fetch protocol (cross-shard provision fetching with peer rotation)
    provision_fetch_protocol: ProvisionFetchProtocol,

    // Transaction validation
    tx_validator: Arc<TransactionValidation>,
    pending_validation: HashSet<Hash>,
    locally_submitted: HashSet<Hash>,

    // Batch accumulators
    validation_batch: BatchAccumulator<Arc<RoutableTransaction>>,
    cross_shard_batch: BatchAccumulator<CrossShardExecutionRequest>,
    execution_vote_batch: BatchAccumulator<ExecutionVoteVerificationItem>,
    execution_certificate_batch: BatchAccumulator<(ExecutionCertificate, Vec<Bls12381G1PublicKey>)>,
    broadcast_vote_batch: ShardedBatchAccumulator<ExecutionVote>,
    broadcast_cert_batch: ShardedBatchAccumulator<Arc<ExecutionCertificate>>,
    committed_header_batch: BatchAccumulator<CommittedHeaderVerificationItem>,

    // Transaction status cache — retains the latest status for every transaction
    // that has emitted a status notification. Bounded LRU cache shared (via Arc)
    // with external consumers (e.g. RPC handlers in production).
    tx_status_cache: Arc<QuickCache<Hash, hyperscale_types::TransactionStatus>>,

    // Cached local shard peers (committee excluding self) — avoids per-call allocation.
    cached_local_peers: Vec<ValidatorId>,

    // Accumulated outputs from this step (for caller to drain)
    emitted_statuses: Vec<(Hash, hyperscale_types::TransactionStatus)>,
    actions_generated: usize,
    pending_timer_ops: Vec<TimerOp>,
}

impl<S, N, D> IoLoop<S, N, D>
where
    S: CommitStore + SubstateStore + ConsensusStore + Send + Sync + 'static,
    N: Network,
    D: Dispatch + 'static,
{
    /// Create a new IoLoop.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        state: NodeStateMachine,
        storage: S,
        executor: RadixExecutor,
        network: N,
        dispatch: D,
        event_sender: crossbeam::channel::Sender<NodeInput>,
        signing_key: Bls12381G1PrivateKey,
        topology: Arc<dyn Topology>,
        config: NodeConfig,
        tx_validator: Arc<TransactionValidation>,
    ) -> Self {
        let local_shard = topology.local_shard();
        let validator_id = topology.local_validator_id();
        let cached_local_peers: Vec<ValidatorId> = topology
            .committee_for_shard(local_shard)
            .iter()
            .filter(|&&v| v != validator_id)
            .copied()
            .collect();
        let b = &config.batch;
        let sync_protocol = SyncProtocol::new(config.sync.clone());
        let fetch_protocol = FetchProtocol::new(config.fetch.clone());
        let provision_fetch_protocol = ProvisionFetchProtocol::new(config.provision_fetch.clone());
        Self {
            state,
            storage: Arc::new(storage),
            executor,
            network,
            dispatch,
            event_sender,
            signing_key: Arc::new(signing_key),
            topology,
            local_shard,
            validator_id,
            prepared_commits: Arc::new(Mutex::new(HashMap::new())),
            cert_cache: Arc::new(QuickCache::new(DEFAULT_CERT_CACHE_SIZE)),
            tx_cache: Arc::new(QuickCache::new(DEFAULT_TX_CACHE_SIZE)),
            pending_cert_verifications: HashMap::new(),
            tx_validator,
            pending_validation: HashSet::new(),
            locally_submitted: HashSet::new(),
            sync_protocol,
            fetch_protocol,
            provision_fetch_protocol,
            validation_batch: BatchAccumulator::new(b.tx_validation_max, b.tx_validation_window),
            cross_shard_batch: BatchAccumulator::new(b.cross_shard_max, b.cross_shard_window),
            execution_vote_batch: BatchAccumulator::new(
                b.execution_vote_max,
                b.execution_vote_window,
            ),
            execution_certificate_batch: BatchAccumulator::new(
                b.execution_certificate_max,
                b.execution_certificate_window,
            ),
            broadcast_vote_batch: ShardedBatchAccumulator::new(
                b.broadcast_vote_max,
                b.broadcast_vote_window,
            ),
            broadcast_cert_batch: ShardedBatchAccumulator::new(
                b.broadcast_cert_max,
                b.broadcast_cert_window,
            ),
            committed_header_batch: BatchAccumulator::new(
                b.committed_header_max,
                b.committed_header_window,
            ),
            cached_local_peers,
            tx_status_cache: Arc::new(QuickCache::new(DEFAULT_TX_STATUS_CACHE_SIZE)),
            emitted_statuses: Vec::new(),
            actions_generated: 0,
            pending_timer_ops: Vec::new(),
        }
    }

    // ─── Time ────────────────────────────────────────────────────────────

    /// Set the state machine's current time.
    ///
    /// Must be called before `step()` to keep the state machine's clock
    /// in sync with the driving environment.
    pub fn set_time(&mut self, now: Duration) {
        self.state.set_time(now);
    }

    // ─── Genesis ─────────────────────────────────────────────────────────

    /// Process actions from genesis initialization.
    ///
    /// `NodeStateMachine::initialize_genesis()` returns actions (timer sets)
    /// that must be processed through the IoLoop's action handler.
    pub fn handle_actions(&mut self, actions: Vec<Action>) {
        for action in actions {
            self.process_action(action);
        }
    }

    /// Access storage mutably and executor simultaneously.
    ///
    /// Needed for operations like genesis that require both references.
    /// Rust's borrow checker can't split borrows through separate method calls.
    ///
    /// After the closure returns (releasing sole Arc ownership), the inbound
    /// request handler is automatically registered with the network.
    ///
    /// # Genesis initialization ordering
    ///
    /// Runners must follow this sequence:
    /// 1. **Engine genesis** via `with_storage_and_executor()` — requires sole Arc
    ///    ownership, then registers the inbound handler automatically
    /// 2. **State-machine genesis** via `state_mut().initialize_genesis()` followed by
    ///    `handle_actions()`, `flush_all_batches()`, and a `StateCommitComplete` event
    ///
    /// # Panics
    ///
    /// Panics if the storage `Arc` has been cloned (e.g., by handler registration
    /// or dispatch closures), since `Arc::get_mut` requires sole ownership.
    pub fn with_storage_and_executor<R>(
        &mut self,
        f: impl FnOnce(&mut S, &RadixExecutor) -> R,
    ) -> R {
        let storage = Arc::get_mut(&mut self.storage).expect(
            "with_storage_and_executor must be called before any spawned closures clone the Arc",
        );
        let result = f(storage, &self.executor);

        // Now sole ownership is released — register handlers.
        self.register_request_handler();
        self.register_gossip_handlers();
        self.register_notification_handlers();

        result
    }

    // ─── Accessors ──────────────────────────────────────────────────────

    /// Access the state machine.
    pub fn state(&self) -> &NodeStateMachine {
        &self.state
    }

    /// Mutably access the state machine.
    pub fn state_mut(&mut self) -> &mut NodeStateMachine {
        &mut self.state
    }

    /// Access the storage.
    pub fn storage(&self) -> &S {
        &self.storage
    }

    /// Mutably access the storage (for initialization/setup).
    pub fn storage_mut(&mut self) -> &mut S {
        Arc::get_mut(&mut self.storage)
            .expect("storage_mut must be called before any spawned closures clone the Arc")
    }

    /// Access the network.
    pub fn network(&self) -> &N {
        &self.network
    }

    /// Look up the latest emitted status for a transaction.
    ///
    /// Returns the most recent status notification for the given transaction
    /// hash, if any status has been emitted. Unlike the per-step
    /// `StepOutput::emitted_statuses`, this cache persists across steps and
    /// survives mempool eviction.
    pub fn tx_status(&self, hash: &Hash) -> Option<hyperscale_types::TransactionStatus> {
        self.tx_status_cache.get(hash)
    }

    /// Access the transaction status cache.
    ///
    /// The cache is an `Arc<QuickCache>` so it can be shared with external
    /// consumers (e.g. RPC handlers) across threads without locking.
    pub fn tx_status_cache(&self) -> &Arc<QuickCache<Hash, hyperscale_types::TransactionStatus>> {
        &self.tx_status_cache
    }

    /// Register per-type request handlers with the network.
    ///
    /// Each handler is a closure that captures shared state and delegates to
    /// the serving function in the corresponding protocol module.
    fn register_request_handler(&self) {
        use crate::protocol::fetch::{serve_certificate_request, serve_transaction_request};
        use crate::protocol::provision_fetch::serve_provision_request;
        use crate::protocol::sync::serve_block_request;
        use hyperscale_messages::request::{
            GetBlockRequest, GetCertificatesRequest, GetProvisionsRequest, GetTransactionsRequest,
        };

        // ── block.request → sync protocol ────────────────────────────

        let storage = Arc::clone(&self.storage);
        self.network
            .register_request_handler::<GetBlockRequest>(move |req| {
                serve_block_request(&*storage, req)
            });

        // ── transaction.request → fetch protocol ─────────────────────

        let storage = Arc::clone(&self.storage);
        let tx_cache = Arc::clone(&self.tx_cache);
        self.network
            .register_request_handler::<GetTransactionsRequest>(move |req| {
                serve_transaction_request(&*storage, &tx_cache, req)
            });

        // ── certificate.request → fetch protocol ─────────────────────

        let storage = Arc::clone(&self.storage);
        let cert_cache = Arc::clone(&self.cert_cache);
        self.network
            .register_request_handler::<GetCertificatesRequest>(move |req| {
                serve_certificate_request(&*storage, &cert_cache, req)
            });

        // ── provision.request → provision fetch protocol ─────────────

        let storage = Arc::clone(&self.storage);
        let topology = Arc::clone(&self.topology);
        self.network
            .register_request_handler::<GetProvisionsRequest>(move |req| {
                serve_provision_request(&*storage, &*topology, req)
            });
    }

    /// Register gossip handlers for broadcast message types (transactions
    /// and committed block headers).
    fn register_gossip_handlers(&self) {
        use hyperscale_network::{GossipVerdict, TopicScope};

        // ── transaction.gossip → ProtocolEvent::TransactionGossipReceived ─
        // The existing step() intercept handles dedup + validation queueing.

        let tx = self.event_sender.clone();
        self.network.register_gossip_handler::<TransactionGossip>(
            TopicScope::Shard,
            move |gossip: TransactionGossip| -> GossipVerdict {
                let _ = tx.send(NodeInput::Protocol(
                    ProtocolEvent::TransactionGossipReceived {
                        tx: gossip.transaction,
                        submitted_locally: false,
                    },
                ));
                GossipVerdict::Accept
            },
        );

        // ── block.committed → pre-filter, then NodeInput::CommittedBlockGossipReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        let local_shard = self.local_shard;
        self.network
            .register_gossip_handler::<hyperscale_messages::CommittedBlockHeaderGossip>(
                TopicScope::Global,
                move |gossip: hyperscale_messages::CommittedBlockHeaderGossip| -> GossipVerdict {
                    let sender = gossip.sender;
                    let header_shard = gossip.committed_header.header.shard_group_id;

                    // Own-shard headers are valid but not needed — accept to forward.
                    if header_shard == local_shard {
                        return GossipVerdict::Accept;
                    }

                    // Verify sender is in the source shard's committee.
                    let committee = topology.committee_for_shard(header_shard);
                    if !committee.contains(&sender) {
                        warn!(
                            sender = sender.0,
                            header_shard = header_shard.0,
                            "Committed header sender not in source shard committee"
                        );
                        return GossipVerdict::Reject;
                    }

                    // Resolve sender's public key.
                    let Some(public_key) = topology.public_key(sender) else {
                        warn!(
                            sender = sender.0,
                            "Could not resolve public key for committed header sender"
                        );
                        return GossipVerdict::Reject;
                    };

                    let _ = tx.send(NodeInput::CommittedBlockGossipReceived {
                        committed_header: gossip.committed_header,
                        sender,
                        public_key,
                        sender_signature: gossip.sender_signature,
                    });
                    GossipVerdict::Accept
                },
            );
    }

    /// Register notification handlers for protocol messages sent via unicast
    /// to known committee members.
    fn register_notification_handlers(&self) {
        // ── block.vote → ProtocolEvent::BlockVoteReceived ────────────

        let tx = self.event_sender.clone();
        self.network
            .register_notification_handler::<BlockVoteNotification>(
                move |gossip: BlockVoteNotification| {
                    let _ = tx.send(NodeInput::Protocol(ProtocolEvent::BlockVoteReceived {
                        vote: gossip.vote,
                    }));
                },
            );

        // ── block.header → verify proposer sig, then ProtocolEvent::BlockHeaderReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        self.network
            .register_notification_handler::<BlockHeaderNotification>(
                move |gossip: BlockHeaderNotification| {
                    let proposer = gossip.header.proposer;
                    let Some(public_key) = topology.public_key(proposer) else {
                        warn!(proposer = proposer.0, "Unknown proposer for block header");
                        return;
                    };
                    let msg = gossip.signing_message();
                    let start = std::time::Instant::now();
                    let valid = hyperscale_types::verify_bls12381_v1(
                        &msg,
                        &public_key,
                        &gossip.proposer_signature,
                    );
                    metrics::record_signature_verification_latency(
                        "block_header",
                        start.elapsed().as_secs_f64(),
                    );
                    if !valid {
                        warn!(
                            proposer = proposer.0,
                            height = gossip.header.height.0,
                            round = gossip.header.round,
                            "Block header proposer signature invalid — dropping"
                        );
                        return;
                    }
                    let (header, manifest, _sig) = gossip.into_parts();
                    let _ = tx.send(NodeInput::Protocol(ProtocolEvent::BlockHeaderReceived {
                        header,
                        manifest,
                    }));
                },
            );

        // ── transaction.certificate → verify sender sig, then NodeInput::TransactionCertificateReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        let local_shard = self.local_shard;
        self.network
            .register_notification_handler::<TransactionCertificateNotification>(
                move |gossip: TransactionCertificateNotification| {
                    let sender = gossip.sender;
                    let committee = topology.committee_for_shard(local_shard);
                    if !committee.contains(&sender) {
                        warn!(
                            sender = sender.0,
                            "Transaction certificate sender not in local shard committee"
                        );
                        return;
                    }

                    let Some(public_key) = topology.public_key(sender) else {
                        warn!(
                            sender = sender.0,
                            "Could not resolve public key for transaction certificate sender"
                        );
                        return;
                    };

                    let msg = gossip.signing_message(local_shard);
                    let start = std::time::Instant::now();
                    let valid = hyperscale_types::verify_bls12381_v1(
                        &msg,
                        &public_key,
                        &gossip.sender_signature,
                    );
                    metrics::record_signature_verification_latency(
                        "tx_cert_gossip",
                        start.elapsed().as_secs_f64(),
                    );
                    if !valid {
                        warn!(
                            sender = sender.0,
                            "Transaction certificate sender signature invalid — dropping"
                        );
                        return;
                    }

                    let _ = tx.send(NodeInput::TransactionCertificateReceived {
                        certificate: gossip.into_certificate(),
                    });
                },
            );

        // ── state.provision.batch → verify sender sig, then ProtocolEvent::StateProvisionsReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        self.network
            .register_notification_handler::<hyperscale_messages::StateProvisionsNotification>(
                move |batch: hyperscale_messages::StateProvisionsNotification| {
                    if batch.provisions.is_empty() {
                        return;
                    }

                    let sender = batch.sender;
                    let source_shard = batch.provisions[0].source_shard;

                    // Verify sender is in the source shard's committee.
                    let committee = topology.committee_for_shard(source_shard);
                    if !committee.contains(&sender) {
                        warn!(
                            sender = sender.0,
                            source_shard = source_shard.0,
                            "State provision sender not in source shard committee"
                        );
                        return;
                    }

                    // Resolve sender's public key.
                    let Some(public_key) = topology.public_key(sender) else {
                        warn!(
                            sender = sender.0,
                            "Could not resolve public key for state provision sender"
                        );
                        return;
                    };

                    let msg = batch.signing_message();
                    let start = std::time::Instant::now();
                    let valid = hyperscale_types::verify_bls12381_v1(
                        &msg,
                        &public_key,
                        &batch.sender_signature,
                    );
                    metrics::record_signature_verification_latency(
                        "state_provision_batch",
                        start.elapsed().as_secs_f64(),
                    );
                    if !valid {
                        warn!(
                            sender = sender.0,
                            source_shard = source_shard.0,
                            "State provision sender signature invalid — dropping"
                        );
                        return;
                    }

                    let provisions = batch.into_provisions();
                    let _ = tx.send(NodeInput::Protocol(
                        ProtocolEvent::StateProvisionsReceived { provisions },
                    ));
                },
            );

        // ── execution.vote.batch → verify sender sig, then ProtocolEvent::ExecutionVoteReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        let local_shard = self.local_shard;
        self.network
            .register_notification_handler::<ExecutionVotesNotification>(
                move |batch: ExecutionVotesNotification| {
                    if batch.votes.is_empty() {
                        return;
                    }

                    let sender = batch.sender;
                    let committee = topology.committee_for_shard(local_shard);
                    if !committee.contains(&sender) {
                        warn!(
                            sender = sender.0,
                            "Execution vote batch sender not in local shard committee"
                        );
                        return;
                    }

                    let Some(public_key) = topology.public_key(sender) else {
                        warn!(
                            sender = sender.0,
                            "Could not resolve public key for execution vote batch sender"
                        );
                        return;
                    };

                    let msg = batch.signing_message(local_shard);
                    let start = std::time::Instant::now();
                    let valid = hyperscale_types::verify_bls12381_v1(
                        &msg,
                        &public_key,
                        &batch.sender_signature,
                    );
                    metrics::record_signature_verification_latency(
                        "exec_vote_batch",
                        start.elapsed().as_secs_f64(),
                    );
                    if !valid {
                        warn!(
                            sender = sender.0,
                            "Execution vote batch sender signature invalid — dropping"
                        );
                        return;
                    }

                    for vote in batch.into_votes() {
                        let _ =
                            tx.send(NodeInput::Protocol(ProtocolEvent::ExecutionVoteReceived {
                                vote,
                            }));
                    }
                },
            );

        // ── execution.certificate.batch → verify sender sig, then ProtocolEvent::ExecutionCertificateReceived ─

        let tx = self.event_sender.clone();
        let topology = Arc::clone(&self.topology);
        let local_shard = self.local_shard;
        self.network
            .register_notification_handler::<ExecutionCertificatesNotification>(
                move |batch: ExecutionCertificatesNotification| {
                    if batch.certificates.is_empty() {
                        return;
                    }

                    let sender = batch.sender;
                    // The sender is from the shard that produced the certificates,
                    // which may differ from the local shard in cross-shard transactions.
                    let source_shard = batch.certificates[0].shard_group_id;
                    if batch
                        .certificates
                        .iter()
                        .any(|c| c.shard_group_id != source_shard)
                    {
                        warn!(
                            sender = sender.0,
                            "Execution certificate batch contains mixed shard_group_ids — dropping"
                        );
                        return;
                    }
                    let committee = topology.committee_for_shard(source_shard);
                    if !committee.contains(&sender) {
                        warn!(
                            sender = sender.0,
                            source_shard = source_shard.0,
                            "Execution certificate batch sender not in source shard committee"
                        );
                        return;
                    }

                    let Some(public_key) = topology.public_key(sender) else {
                        warn!(
                            sender = sender.0,
                            "Could not resolve public key for execution certificate batch sender"
                        );
                        return;
                    };

                    let msg = batch.signing_message(local_shard);
                    let start = std::time::Instant::now();
                    let valid = hyperscale_types::verify_bls12381_v1(
                        &msg,
                        &public_key,
                        &batch.sender_signature,
                    );
                    metrics::record_signature_verification_latency(
                        "exec_cert_batch",
                        start.elapsed().as_secs_f64(),
                    );
                    if !valid {
                        warn!(
                            sender = sender.0,
                            "Execution certificate batch sender signature invalid — dropping"
                        );
                        return;
                    }

                    for cert in batch.into_certificates() {
                        let _ = tx.send(NodeInput::Protocol(
                            ProtocolEvent::ExecutionCertificateReceived { cert },
                        ));
                    }
                },
            );
    }

    // ─── Event Processing ───────────────────────────────────────────────

    /// Process a single event through the state machine and handle all resulting actions.
    ///
    /// Returns a [`StepOutput`] containing emitted transaction statuses and timer
    /// operations. Sync/fetch I/O is handled internally via the Network trait.
    ///
    /// # Caller protocol
    ///
    /// After each call to `step()`, the runner should:
    /// 1. Flush batches — either [`flush_all_batches()`] (simulation) or
    ///    [`flush_expired_batches()`] (production, with wall-clock time)
    /// 2. Process `timer_ops` from the returned [`StepOutput`]
    /// 3. Process `emitted_statuses` from the returned [`StepOutput`]
    /// 4. Drain any events produced through the event channel (simulation only —
    ///    production receives these via its crossbeam channel receivers)
    pub fn step(&mut self, event: NodeInput) -> StepOutput {
        self.emitted_statuses.clear();
        self.actions_generated = 0;
        self.pending_timer_ops.clear();

        match event {
            // ── Transaction validation pipeline ────────────────────────
            //
            // TransactionGossipReceived and SubmitTransaction are routed
            // through the validation batch pipeline. Validated transactions
            // re-enter as TransactionValidated, which is converted into
            // TransactionGossipReceived for the state machine.
            NodeInput::TransactionValidated {
                tx,
                submitted_locally,
            } => {
                let tx_hash = tx.hash();
                self.pending_validation.remove(&tx_hash);
                let is_local = submitted_locally || self.locally_submitted.remove(&tx_hash);
                self.tx_cache.insert(tx_hash, Arc::clone(&tx));
                self.actions_generated = 0;
                self.feed_event(ProtocolEvent::TransactionGossipReceived {
                    tx,
                    submitted_locally: is_local,
                });
            }

            // Intercept gossip-received transactions for validation.
            NodeInput::Protocol(ProtocolEvent::TransactionGossipReceived { tx, .. }) => {
                let tx_hash = tx.hash();
                if self.tx_cache.get(&tx_hash).is_none()
                    && !self.state.mempool().is_tombstoned(&tx_hash)
                {
                    self.pending_validation.insert(tx_hash);
                    self.queue_validation(tx);
                }
            }

            NodeInput::SubmitTransaction { tx } => {
                let tx_hash = tx.hash();

                // Gossip to all relevant shards.
                for shard in self.topology.all_shards_for_transaction(&tx) {
                    let gossip = TransactionGossip::from_arc(Arc::clone(&tx));
                    self.network.broadcast_to_shard(shard, &gossip);
                }

                // Track as locally submitted for latency metrics.
                self.locally_submitted.insert(tx_hash);

                // Queue for validation if not already in pipeline or cached.
                if !self.pending_validation.contains(&tx_hash)
                    && self.tx_cache.get(&tx_hash).is_none()
                {
                    self.pending_validation.insert(tx_hash);
                    self.queue_validation(tx);
                }
            }

            NodeInput::TransactionCertificateReceived { certificate } => {
                self.handle_received_certificate(certificate);
            }

            NodeInput::CertificateSignatureVerified {
                tx_hash,
                shard,
                valid,
            } => {
                self.handle_cert_verification_result(tx_hash, shard, valid);
            }

            // ── Sync protocol ──────────────────────────────────────────
            NodeInput::SyncBlockResponseReceived { height, block } => {
                let outputs = self
                    .sync_protocol
                    .handle(SyncInput::BlockResponseReceived { height, block });
                self.process_sync_outputs(outputs);
            }

            NodeInput::SyncBlockFetchFailed { height } => {
                let outputs = self
                    .sync_protocol
                    .handle(SyncInput::BlockFetchFailed { height });
                self.process_sync_outputs(outputs);
            }

            // ── Fetch protocol ─────────────────────────────────────────
            NodeInput::TransactionReceived {
                block_hash,
                transactions,
            } => {
                let outputs = self
                    .fetch_protocol
                    .handle(FetchInput::TransactionsReceived {
                        block_hash,
                        transactions,
                    });
                self.process_fetch_outputs(outputs);
            }

            NodeInput::CertificateReceived {
                block_hash,
                certificates,
            } => {
                let outputs = self
                    .fetch_protocol
                    .handle(FetchInput::CertificatesReceived {
                        block_hash,
                        certificates,
                    });
                self.process_fetch_outputs(outputs);
            }

            NodeInput::FetchTransactionsFailed { block_hash, hashes } => {
                let outputs = self.fetch_protocol.handle(FetchInput::FetchFailed {
                    block_hash,
                    kind: FetchKind::Transaction,
                    hashes,
                });
                self.process_fetch_outputs(outputs);
                // Tick to retry pending fetches.
                let tick_outputs = self.fetch_protocol.handle(FetchInput::Tick);
                self.process_fetch_outputs(tick_outputs);
            }

            NodeInput::FetchCertificatesFailed { block_hash, hashes } => {
                let outputs = self.fetch_protocol.handle(FetchInput::FetchFailed {
                    block_hash,
                    kind: FetchKind::Certificate,
                    hashes,
                });
                self.process_fetch_outputs(outputs);
                // Tick to retry pending fetches.
                let tick_outputs = self.fetch_protocol.handle(FetchInput::Tick);
                self.process_fetch_outputs(tick_outputs);
                self.update_fetch_tick_timer();
            }

            NodeInput::FetchTick => {
                let outputs = self.fetch_protocol.handle(FetchInput::Tick);
                self.process_fetch_outputs(outputs);
                // Also tick the provision fetch protocol.
                let prov_outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Tick);
                self.process_provision_fetch_outputs(prov_outputs);
                self.update_fetch_tick_timer();
            }

            // ── Provision fetch protocol ──────────────────────────────
            NodeInput::ProvisionFetchReceived {
                source_shard,
                block_height,
                provisions,
            } => {
                let outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Received {
                        source_shard,
                        block_height,
                        provisions,
                    });
                self.process_provision_fetch_outputs(outputs);
                self.update_fetch_tick_timer();
            }

            NodeInput::ProvisionFetchFailed {
                source_shard,
                block_height,
            } => {
                let outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Failed {
                        source_shard,
                        block_height,
                    });
                self.process_provision_fetch_outputs(outputs);
                // Tick to retry with next peer immediately.
                let tick_outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Tick);
                self.process_provision_fetch_outputs(tick_outputs);
                self.update_fetch_tick_timer();
            }

            // ── Committed header validated (sender sig verified) ────────
            NodeInput::CommittedHeaderValidated {
                committed_header,
                sender,
            } => {
                self.feed_event(ProtocolEvent::RemoteBlockCommitted {
                    committed_header,
                    sender,
                });
            }

            // ── Committed block gossip (pre-filtered) ─────────────────
            //
            // Handler closure already verified sender's committee membership
            // and resolved the public key. Queue for batched BLS verification.
            NodeInput::CommittedBlockGossipReceived {
                committed_header,
                sender,
                public_key,
                sender_signature,
            } => {
                let item: CommittedHeaderVerificationItem =
                    (committed_header, sender, public_key, sender_signature);
                if self.committed_header_batch.push(item, self.state.now()) {
                    self.flush_committed_header_verifications();
                }
            }

            // ── Provisions ready (from execution pool) ─────────────────
            //
            // The FetchAndBroadcastProvisions delegated action built provisions
            // grouped by target shard. Broadcast one batch per shard.
            NodeInput::ProvisionsReady { batches } => {
                for (shard, provisions) in batches {
                    let msg = hyperscale_types::state_provision_batch_message(
                        self.local_shard,
                        shard,
                        provisions[0].block_height,
                        &provisions,
                    );
                    let sig = self.signing_key.sign_v1(&msg);
                    let batch = hyperscale_messages::StateProvisionsNotification::new(
                        provisions,
                        self.validator_id,
                        sig,
                    );
                    let recipients = self.peers_for_shard(shard);
                    self.network.notify(&recipients, &batch);
                }
            }

            // ── Protocol events → state machine ────────────────────────
            NodeInput::Protocol(pe) => {
                // Broadcast self-generated execution votes returning from dispatch.
                // Votes from peers arrive via network gossip.
                if let ProtocolEvent::ExecutionVoteReceived { ref vote } = pe {
                    if vote.validator == self.validator_id {
                        self.accumulate_broadcast_vote(self.local_shard, vote.clone());
                    }
                }

                self.feed_event(pe);
            }
        }

        self.drain_pending_output()
    }

    /// Drain accumulated outputs (statuses, timer ops) without processing an event.
    ///
    /// Used after `handle_actions()` to collect outputs produced by those actions.
    pub fn drain_pending_output(&mut self) -> StepOutput {
        StepOutput {
            emitted_statuses: std::mem::take(&mut self.emitted_statuses),
            actions_generated: self.actions_generated,
            timer_ops: std::mem::take(&mut self.pending_timer_ops),
        }
    }

    /// Feed a protocol event to the state machine and process all resulting actions.
    ///
    /// This is the common pattern used throughout IoLoop: route an event through
    /// the state machine, then dispatch each resulting action.
    fn feed_event(&mut self, event: ProtocolEvent) {
        let actions = self.state.handle(event);
        self.actions_generated += actions.len();
        for action in actions {
            self.process_action(action);
        }
    }

    /// Flush any batch accumulators whose deadlines have expired.
    ///
    /// Call this with the current time before processing events. In production,
    /// the loop calls this with wall-clock time. In simulation, the harness
    /// calls it with logical time.
    pub fn flush_expired_batches(&mut self, now: Duration) {
        if self.validation_batch.is_expired(now) {
            self.flush_validation_batch();
        }
        if self.cross_shard_batch.is_expired(now) {
            self.flush_cross_shard_executions();
        }
        if self.execution_vote_batch.is_expired(now) {
            self.flush_execution_vote_verifications();
        }
        if self.execution_certificate_batch.is_expired(now) {
            self.flush_execution_certificate_verifications();
        }
        if self.broadcast_vote_batch.is_expired(now) {
            self.flush_broadcast_votes();
        }
        if self.broadcast_cert_batch.is_expired(now) {
            self.flush_broadcast_certs();
        }
        if self.committed_header_batch.is_expired(now) {
            self.flush_committed_header_verifications();
        }

        // Clean up stale pending certificate verifications.
        let before = self.pending_cert_verifications.len();
        self.pending_cert_verifications.retain(|_, pending| {
            now.saturating_sub(pending.created_at) < PENDING_CERT_VERIFICATION_TIMEOUT
        });
        let cleaned = before - self.pending_cert_verifications.len();
        if cleaned > 0 {
            warn!(
                cleaned,
                remaining = self.pending_cert_verifications.len(),
                "Cleaned up stale pending certificate verifications"
            );
        }
    }

    /// Get the nearest batch deadline, if any.
    ///
    /// Used by the production `run()` loop for `recv_timeout()` and by the
    /// simulation harness to know when to schedule a flush.
    pub fn nearest_batch_deadline(&self) -> Option<Duration> {
        [
            self.validation_batch.deadline(),
            self.cross_shard_batch.deadline(),
            self.execution_vote_batch.deadline(),
            self.execution_certificate_batch.deadline(),
            self.broadcast_vote_batch.deadline(),
            self.broadcast_cert_batch.deadline(),
            self.committed_header_batch.deadline(),
        ]
        .into_iter()
        .flatten()
        .min()
    }

    // ─── Action Processing ──────────────────────────────────────────────

    /// Process a single action from the state machine.
    fn process_action(&mut self, action: Action) {
        match action {
            // ═══════════════════════════════════════════════════════════
            // Timers
            // ═══════════════════════════════════════════════════════════
            Action::SetTimer { id, duration } => {
                self.pending_timer_ops.push(TimerOp::Set { id, duration });
            }
            Action::CancelTimer { id } => {
                self.pending_timer_ops.push(TimerOp::Cancel { id });
            }

            // ═══════════════════════════════════════════════════════════
            // Internal events
            // ═══════════════════════════════════════════════════════════
            Action::Continuation(pe) => {
                let _ = self.event_sender.send(NodeInput::Protocol(pe));
            }

            // ═══════════════════════════════════════════════════════════
            // Network broadcasts — immediate (non-batched)
            // ═══════════════════════════════════════════════════════════
            Action::BroadcastBlockHeader { shard: _, header } => {
                self.network.notify(&self.cached_local_peers, &*header);
            }
            Action::BroadcastBlockVote { shard: _, vote } => {
                self.network.notify(&self.cached_local_peers, &vote);
            }
            Action::BroadcastTransaction { shard, gossip } => {
                self.network.broadcast_to_shard(shard, &*gossip);
            }
            Action::BroadcastTransactionCertificate { shard: _, gossip } => {
                self.network.notify(&self.cached_local_peers, &gossip);
            }
            Action::BroadcastCommittedBlockHeader { gossip } => {
                self.network.broadcast_global(&gossip);
            }

            // ═══════════════════════════════════════════════════════════
            // Network broadcasts — batched
            // ═══════════════════════════════════════════════════════════
            Action::BroadcastExecutionVote { shard, vote } => {
                self.accumulate_broadcast_vote(shard, vote);
            }
            Action::BroadcastExecutionCertificate { shard, certificate } => {
                self.accumulate_broadcast_cert(shard, certificate);
            }
            // ═══════════════════════════════════════════════════════════
            // Delegated work — batched (accumulated for batch dispatch)
            // ═══════════════════════════════════════════════════════════
            Action::VerifyAndAggregateExecutionVotes { tx_hash, votes } => {
                self.accumulate_execution_vote_verification((tx_hash, votes));
            }
            Action::VerifyExecutionCertificateSignature {
                certificate,
                public_keys,
            } => {
                self.accumulate_execution_certificate_verification(certificate, public_keys);
            }
            Action::ExecuteCrossShardTransaction {
                tx_hash,
                transaction,
                provisions,
            } => {
                self.accumulate_cross_shard_execution(tx_hash, transaction, provisions);
            }

            // ═══════════════════════════════════════════════════════════
            // Delegated work — immediate dispatch
            // ═══════════════════════════════════════════════════════════
            Action::VerifyAndBuildQuorumCertificate { .. }
            | Action::VerifyQcSignature { .. }
            | Action::VerifyCommitmentProof { .. }
            | Action::VerifyStateRoot { .. }
            | Action::VerifyTransactionRoot { .. }
            | Action::BuildProposal { .. }
            | Action::AggregateExecutionCertificate { .. }
            | Action::VerifyStateProvisions { .. }
            | Action::ExecuteTransactions { .. }
            | Action::SpeculativeExecute { .. }
            | Action::FetchAndBroadcastProvisions { .. } => {
                self.dispatch_delegated_action(action);
            }

            // ═══════════════════════════════════════════════════════════
            // Storage
            // ═══════════════════════════════════════════════════════════
            Action::PersistBlock { .. }
            | Action::PersistTransactionCertificate { .. }
            | Action::PersistAndBroadcastVote { .. }
            | Action::FetchBlock { .. }
            | Action::FetchChainMetadata => {
                self.process_storage_action(action);
            }

            // ═══════════════════════════════════════════════════════════
            // Block commit + notifications
            // ═══════════════════════════════════════════════════════════
            Action::EmitCommittedBlock { block, qc } => {
                self.process_block_commit(block, qc);
            }
            Action::EmitTransactionStatus {
                tx_hash,
                status,
                added_at,
                cross_shard,
                submitted_locally,
            } => {
                debug!(?tx_hash, ?status, "Transaction status");
                if status.is_final() && submitted_locally {
                    let now = self.state.now();
                    let latency_secs = now.saturating_sub(added_at).as_secs_f64();
                    metrics::record_transaction_finalized(latency_secs, cross_shard);
                }
                self.tx_status_cache.insert(tx_hash, status.clone());
                self.emitted_statuses.push((tx_hash, status));
            }

            // ═══════════════════════════════════════════════════════════
            // Sync / Fetch / Provision recovery
            // ═══════════════════════════════════════════════════════════
            Action::StartSync { .. }
            | Action::FetchTransactions { .. }
            | Action::FetchCertificates { .. }
            | Action::CancelFetch { .. }
            | Action::RequestMissingProvisions { .. } => {
                self.process_sync_fetch_action(action);
            }

            // ═══════════════════════════════════════════════════════════
            // Global consensus / epoch (not yet implemented)
            // ═══════════════════════════════════════════════════════════
            Action::ProposeGlobalBlock { .. }
            | Action::BroadcastGlobalBlockVote { .. }
            | Action::TransitionEpoch { .. }
            | Action::MarkValidatorReady { .. }
            | Action::InitiateShardSplit { .. }
            | Action::CompleteShardSplit { .. }
            | Action::InitiateShardMerge { .. }
            | Action::CompleteShardMerge { .. }
            | Action::PersistEpochConfig { .. }
            | Action::FetchEpochConfig { .. } => {}
        }
    }

    // ─── Action Handler Groups ──────────────────────────────────────────

    /// Process storage read/write actions.
    fn process_storage_action(&mut self, action: Action) {
        match action {
            Action::PersistBlock { block, qc } => {
                let height = block.header.height;
                ConsensusStore::put_block(&*self.storage, height, &block, &qc);
            }
            Action::PersistTransactionCertificate { certificate } => {
                // Populate cert cache before persisting — serves peer fetch requests
                // from memory even if storage write hasn't completed.
                self.cert_cache
                    .insert(certificate.transaction_hash, Arc::new(certificate.clone()));
                self.storage.store_certificate(&certificate);
                // Notify local shard peers about cross-shard certificates.
                if certificate.shard_proofs.len() > 1 {
                    let msg = hyperscale_types::tx_cert_gossip_message(
                        self.local_shard,
                        &certificate.transaction_hash,
                    );
                    let sig = self.signing_key.sign_v1(&msg);
                    let gossip = TransactionCertificateNotification::new(
                        certificate,
                        self.validator_id,
                        sig,
                    );
                    self.network.notify(&self.cached_local_peers, &gossip);
                }
            }
            Action::PersistAndBroadcastVote {
                height,
                round,
                block_hash,
                shard: _,
                vote,
            } => {
                // BFT Safety: persist vote BEFORE broadcasting.
                self.storage.put_own_vote(height.0, round, block_hash);
                trace!(
                    height = height.0,
                    round,
                    block_hash = ?block_hash,
                    "Persisted own vote"
                );
                self.network.notify(&self.cached_local_peers, &vote);
            }
            Action::FetchBlock { height } => {
                let block = self.storage.get_block(height);
                let _ = self
                    .event_sender
                    .send(NodeInput::Protocol(ProtocolEvent::BlockFetched {
                        height,
                        block: block.map(|(b, _)| b),
                    }));
            }
            Action::FetchChainMetadata => {
                let height = self.storage.committed_height();
                let hash = self.storage.committed_hash();
                let qc = self.storage.latest_qc();
                let _ = self.event_sender.send(NodeInput::Protocol(
                    ProtocolEvent::ChainMetadataFetched { height, hash, qc },
                ));
            }
            _ => unreachable!(),
        }
    }

    /// Process a committed block — apply state, emit metrics, feed sync protocol.
    fn process_block_commit(
        &mut self,
        block: hyperscale_types::Block,
        qc: hyperscale_types::QuorumCertificate,
    ) {
        let block_hash = block.hash();
        let height = block.header.height;
        debug!(height = height.0, ?block_hash, "Block committed");

        // Block commit latency: time from proposal timestamp to now.
        let now_ms = self.state.now().as_millis() as u64;
        let commit_latency_secs = (now_ms.saturating_sub(block.header.timestamp)) as f64 / 1000.0;
        metrics::record_block_committed(height.0, commit_latency_secs);
        metrics::set_block_height(height.0);
        metrics::set_txs_with_commitment_proof(block.commitment_proofs.len());

        // Livelock metrics for deferrals in this block.
        for _deferral in &block.deferred {
            metrics::record_livelock_deferral();
            metrics::record_livelock_cycle_detected();
        }
        metrics::set_livelock_deferred_count(self.state.livelock().stats().pending_deferrals);

        let prepared = self.prepared_commits.lock().unwrap().remove(&block_hash);

        // Commit state writes (fast path uses prepared handle, slow
        // path recomputes from certificates).
        if !block.certificates.is_empty() {
            let result = if let Some(prepared) = prepared {
                self.storage.commit_prepared_block(prepared)
            } else {
                self.storage
                    .commit_block(&block.certificates, self.local_shard)
            };

            // Persist committed metadata AFTER state is applied.
            ConsensusStore::set_committed_state(&*self.storage, height, block_hash, &qc);
            ConsensusStore::prune_own_votes(&*self.storage, height.0);

            let _ =
                self.event_sender
                    .send(NodeInput::Protocol(ProtocolEvent::StateCommitComplete {
                        height: height.0,
                        state_version: result.state_version,
                        state_root: result.state_root,
                    }));
        } else {
            // Empty block — no state changes, but still update
            // committed metadata.
            ConsensusStore::set_committed_state(&*self.storage, height, block_hash, &qc);
            ConsensusStore::prune_own_votes(&*self.storage, height.0);
        }

        // Feed committed height to sync protocol.
        let outputs = self
            .sync_protocol
            .handle(SyncInput::BlockCommitted { height: height.0 });
        self.process_sync_outputs(outputs);
    }

    /// Process sync, fetch, and provision recovery actions.
    fn process_sync_fetch_action(&mut self, action: Action) {
        match action {
            Action::StartSync {
                target_height,
                target_hash,
            } => {
                let outputs = self.sync_protocol.handle(SyncInput::StartSync {
                    target_height,
                    target_hash,
                });
                self.process_sync_outputs(outputs);
            }
            Action::FetchTransactions {
                block_hash,
                proposer,
                tx_hashes,
            } => {
                self.fetch_protocol.handle(FetchInput::RequestTransactions {
                    block_hash,
                    proposer,
                    tx_hashes,
                });
                let outputs = self.fetch_protocol.handle(FetchInput::Tick);
                self.process_fetch_outputs(outputs);
                self.update_fetch_tick_timer();
            }
            Action::FetchCertificates {
                block_hash,
                proposer,
                cert_hashes,
            } => {
                self.fetch_protocol.handle(FetchInput::RequestCertificates {
                    block_hash,
                    proposer,
                    cert_hashes,
                });
                let outputs = self.fetch_protocol.handle(FetchInput::Tick);
                self.process_fetch_outputs(outputs);
                self.update_fetch_tick_timer();
            }
            Action::CancelFetch { block_hash } => {
                self.fetch_protocol
                    .handle(FetchInput::CancelFetch { block_hash });
            }
            Action::RequestMissingProvisions {
                source_shard,
                block_height,
                proposer,
            } => {
                let peers: Vec<ValidatorId> =
                    self.topology.committee_for_shard(source_shard).into_owned();
                debug!(
                    source_shard = source_shard.0,
                    block_height = block_height.0,
                    proposer = proposer.0,
                    peer_count = peers.len(),
                    "Requesting missing provisions from source shard"
                );
                let outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Request {
                        source_shard,
                        block_height,
                        target_shard: self.local_shard,
                        peers,
                        preferred_peer: proposer,
                    });
                self.process_provision_fetch_outputs(outputs);
                let tick_outputs = self
                    .provision_fetch_protocol
                    .handle(ProvisionFetchInput::Tick);
                self.process_provision_fetch_outputs(tick_outputs);
                self.update_fetch_tick_timer();
            }
            _ => unreachable!(),
        }
    }

    // ─── Delegated Work ─────────────────────────────────────────────────

    /// Dispatch a delegated action to the appropriate thread pool.
    ///
    /// Spawns the work as a fire-and-forget closure. Results return via the
    /// `event_sender` channel and are processed on a future `step()` call.
    /// With `SyncDispatch` (simulation), `spawn_*` runs inline so events
    /// enter the channel immediately and are drained by the harness.
    fn dispatch_delegated_action(&mut self, action: Action) {
        let is_speculative = matches!(action, Action::SpeculativeExecute { .. });
        let is_execution = is_speculative || matches!(action, Action::ExecuteTransactions { .. });
        let pool = action_handler::dispatch_pool_for(&action)
            .expect("dispatch_delegated_action called for delegated actions only");

        // Clone cheap shared state for the 'static spawn closure.
        let storage = Arc::clone(&self.storage);
        let executor = self.executor.clone();
        let topology = Arc::clone(&self.topology);
        let signing_key = Arc::clone(&self.signing_key);
        let dispatch = self.dispatch.clone();
        let local_shard = self.local_shard;
        let validator_id = self.validator_id;
        let prepared_commits = Arc::clone(&self.prepared_commits);
        let event_tx = self.event_sender.clone();

        let spawn_fn = move || {
            let start = std::time::Instant::now();
            let ctx = ActionContext {
                storage: &*storage,
                executor: &executor,
                topology: &*topology,
                signing_key: &signing_key,
                local_shard,
                validator_id,
                dispatch: &dispatch,
            };
            if let Some(result) = action_handler::handle_delegated_action(action, &ctx) {
                if is_execution {
                    let elapsed = start.elapsed().as_secs_f64();
                    if is_speculative {
                        metrics::record_speculative_execution_latency(elapsed);
                    } else {
                        metrics::record_execution_latency(elapsed);
                    }
                }
                if let Some((hash, prepared)) = result.prepared_commit {
                    prepared_commits.lock().unwrap().insert(hash, prepared);
                }
                for event in result.events {
                    let _ = event_tx.send(event);
                }
            }
        };

        match pool {
            DispatchPool::ConsensusCrypto => self.dispatch.spawn_consensus_crypto(spawn_fn),
            DispatchPool::Crypto => self.dispatch.spawn_crypto(spawn_fn),
            DispatchPool::Execution => self.dispatch.spawn_execution(spawn_fn),
        }
    }

    /// Local shard committee excluding self, for use as the `peers` argument
    /// to `network.request()`.
    fn local_peers(&self) -> &[ValidatorId] {
        &self.cached_local_peers
    }

    /// Committee for a shard excluding self, for use as notify recipients.
    fn peers_for_shard(&self, shard: ShardGroupId) -> Vec<ValidatorId> {
        let vid = self.validator_id;
        self.topology
            .committee_for_shard(shard)
            .iter()
            .copied()
            .filter(|&v| v != vid)
            .collect()
    }

    /// Process SyncProtocol outputs internally.
    ///
    /// DeliverBlock and SyncComplete are fed directly to the state machine
    /// (no round-trip through the runner). FetchBlock uses the Network trait.
    fn process_sync_outputs(&mut self, outputs: Vec<SyncOutput>) {
        for output in outputs {
            match output {
                SyncOutput::FetchBlock { height } => {
                    use hyperscale_messages::request::GetBlockRequest;
                    let es = self.event_sender.clone();
                    let peers = self.local_peers();
                    self.network.request(
                        peers,
                        None,
                        GetBlockRequest {
                            height: hyperscale_types::BlockHeight(height),
                        },
                        Box::new(move |result| match result {
                            Ok(resp) => {
                                let block = match (resp.block, resp.qc) {
                                    (Some(b), Some(q)) => Some((b, q)),
                                    _ => None,
                                };
                                let _ = es.send(NodeInput::SyncBlockResponseReceived {
                                    height,
                                    block: Box::new(block),
                                });
                            }
                            Err(_) => {
                                let _ = es.send(NodeInput::SyncBlockFetchFailed { height });
                            }
                        }),
                    );
                }
                SyncOutput::DeliverBlock { block, qc } => {
                    metrics::record_sync_block_received_by_bft();
                    metrics::record_sync_block_submitted_for_verification();
                    self.feed_event(ProtocolEvent::SyncBlockReadyToApply {
                        block: *block,
                        qc: *qc,
                    });
                }
                SyncOutput::SyncComplete { height } => {
                    self.feed_event(ProtocolEvent::SyncComplete { height });
                }
            }
        }
    }

    /// Process FetchProtocol outputs.
    ///
    /// FetchTransactions/FetchCertificates use the Network trait to make requests.
    /// DeliverTransactions/DeliverCertificates feed events directly to the state machine.
    fn process_fetch_outputs(&mut self, outputs: Vec<FetchOutput>) {
        for output in outputs {
            match output {
                FetchOutput::FetchTransactions {
                    block_hash,
                    proposer,
                    tx_hashes,
                } => {
                    use hyperscale_messages::request::GetTransactionsRequest;
                    let es = self.event_sender.clone();
                    let bh = block_hash;
                    let hs = tx_hashes.clone();
                    let peers = self.local_peers();
                    self.network.request(
                        peers,
                        Some(proposer),
                        GetTransactionsRequest::new(block_hash, tx_hashes),
                        Box::new(move |result| match result {
                            Ok(resp) => {
                                let _ = es.send(NodeInput::TransactionReceived {
                                    block_hash: bh,
                                    transactions: resp.into_transactions(),
                                });
                            }
                            Err(_) => {
                                let _ = es.send(NodeInput::FetchTransactionsFailed {
                                    block_hash: bh,
                                    hashes: hs,
                                });
                            }
                        }),
                    );
                }
                FetchOutput::FetchCertificates {
                    block_hash,
                    proposer,
                    cert_hashes,
                } => {
                    use hyperscale_messages::request::GetCertificatesRequest;
                    let es = self.event_sender.clone();
                    let bh = block_hash;
                    let hs = cert_hashes.clone();
                    let peers = self.local_peers();
                    self.network.request(
                        peers,
                        Some(proposer),
                        GetCertificatesRequest::new(block_hash, cert_hashes),
                        Box::new(move |result| match result {
                            Ok(resp) => {
                                let _ = es.send(NodeInput::CertificateReceived {
                                    block_hash: bh,
                                    certificates: resp.into_certificates(),
                                });
                            }
                            Err(_) => {
                                let _ = es.send(NodeInput::FetchCertificatesFailed {
                                    block_hash: bh,
                                    hashes: hs,
                                });
                            }
                        }),
                    );
                }
                FetchOutput::DeliverTransactions {
                    block_hash,
                    transactions,
                } => {
                    self.feed_event(ProtocolEvent::TransactionFetchDelivered {
                        block_hash,
                        transactions,
                    });
                }
                FetchOutput::DeliverCertificates {
                    block_hash,
                    certificates,
                } => {
                    // Persist fetched certificates to storage so they survive restarts.
                    for cert in &certificates {
                        self.storage.store_certificate(cert);
                    }
                    self.feed_event(ProtocolEvent::CertificateFetchDelivered {
                        block_hash,
                        certificates,
                    });
                }
            }
        }
    }

    /// Process ProvisionFetchProtocol outputs.
    ///
    /// `Fetch` uses the Network trait to send a single-peer request.
    /// `Deliver` feeds provisions into the state machine via `StateProvisionsReceived`.
    fn process_provision_fetch_outputs(&mut self, outputs: Vec<ProvisionFetchOutput>) {
        for output in outputs {
            match output {
                ProvisionFetchOutput::Fetch {
                    source_shard,
                    block_height,
                    target_shard,
                    peer,
                } => {
                    use hyperscale_messages::request::GetProvisionsRequest;
                    let request = GetProvisionsRequest {
                        block_height,
                        target_shard,
                    };
                    let sender = self.event_sender.clone();
                    self.network.request(
                        &[peer],
                        None,
                        request,
                        Box::new(move |result| match result {
                            Ok(response) => match response.provisions {
                                Some(provisions) if !provisions.is_empty() => {
                                    let _ = sender.send(NodeInput::ProvisionFetchReceived {
                                        source_shard,
                                        block_height,
                                        provisions,
                                    });
                                }
                                Some(_) => {
                                    // Empty provisions — no matching transactions for
                                    // our shard at this block height. Treat as success
                                    // (removes the pending entry).
                                    let _ = sender.send(NodeInput::ProvisionFetchReceived {
                                        source_shard,
                                        block_height,
                                        provisions: vec![],
                                    });
                                }
                                None => {
                                    // Peer cannot serve (state version GC'd) → fail
                                    // so the protocol tries the next peer.
                                    let _ = sender.send(NodeInput::ProvisionFetchFailed {
                                        source_shard,
                                        block_height,
                                    });
                                }
                            },
                            Err(_) => {
                                let _ = sender.send(NodeInput::ProvisionFetchFailed {
                                    source_shard,
                                    block_height,
                                });
                            }
                        }),
                    );
                }
                ProvisionFetchOutput::Deliver { provisions } => {
                    if !provisions.is_empty() {
                        self.feed_event(ProtocolEvent::StateProvisionsReceived { provisions });
                    }
                }
            }
        }
    }

    /// Interval for the periodic fetch tick timer.
    const FETCH_TICK_INTERVAL: Duration = Duration::from_millis(200);

    /// Set or cancel the periodic fetch tick timer based on protocol state.
    ///
    /// When the fetch protocol has pending work, a recurring timer fires
    /// `NodeInput::FetchTick` to retry deferred or failed fetch operations.
    /// When all fetches are complete, the timer is cancelled.
    fn update_fetch_tick_timer(&mut self) {
        let status = self.fetch_protocol.status();
        let has_fetch_work = status.pending_tx_blocks > 0 || status.pending_cert_blocks > 0;
        let has_provision_work = self.provision_fetch_protocol.has_pending();
        if has_fetch_work || has_provision_work {
            self.pending_timer_ops.push(TimerOp::Set {
                id: TimerId::FetchTick,
                duration: Self::FETCH_TICK_INTERVAL,
            });
        } else {
            self.pending_timer_ops.push(TimerOp::Cancel {
                id: TimerId::FetchTick,
            });
        }
    }

    // ─── Transaction Validation Batching ──────────────────────────────

    /// Queue a transaction for batch validation.
    fn queue_validation(&mut self, tx: Arc<RoutableTransaction>) {
        if self.validation_batch.push(tx, self.state.now()) {
            self.flush_validation_batch();
        }
    }

    /// Flush the validation batch, dispatching to the tx_validation pool.
    ///
    /// Valid transactions are sent back as `TransactionGossipReceived` events
    /// through the event channel. IoLoop recognises them via `pending_validation`
    /// and passes them through to the state machine.
    fn flush_validation_batch(&mut self) {
        let batch = self.validation_batch.take();
        if batch.is_empty() {
            return;
        }

        let validator = self.tx_validator.clone();
        let event_tx = self.event_sender.clone();
        let dispatch = self.dispatch.clone();
        self.dispatch.spawn_tx_validation(move || {
            // Validate in parallel across all tx_validation pool threads,
            // then send results sequentially to preserve ordering.
            let results: Vec<bool> =
                dispatch.map_tx_validation(&batch, |tx| validator.validate_transaction(tx).is_ok());

            for (tx, valid) in batch.into_iter().zip(results) {
                if valid {
                    let _ = event_tx.send(NodeInput::TransactionValidated {
                        tx,
                        submitted_locally: false, // IoLoop sets from locally_submitted
                    });
                }
            }
        });
    }

    /// Flush a batch of cross-shard executions to the execution pool.
    fn flush_cross_shard_executions(&mut self) {
        let requests = self.cross_shard_batch.take();
        if requests.is_empty() {
            return;
        }

        let storage = Arc::clone(&self.storage);
        let executor = self.executor.clone();
        let topology = Arc::clone(&self.topology);
        let signing_key = Arc::clone(&self.signing_key);
        let dispatch = self.dispatch.clone();
        let local_shard = self.local_shard;
        let validator_id = self.validator_id;
        let event_tx = self.event_sender.clone();

        self.dispatch.spawn_execution(move || {
            let start = std::time::Instant::now();
            let votes: Vec<_> = dispatch.map_execution(&requests, |req| {
                hyperscale_execution::handlers::execute_and_sign_cross_shard(
                    &executor,
                    &*storage,
                    req.tx_hash,
                    &req.transaction,
                    &req.provisions,
                    &signing_key,
                    local_shard,
                    validator_id,
                    &*topology,
                )
            });
            metrics::record_execution_latency(start.elapsed().as_secs_f64());
            for vote in votes {
                let _ = event_tx.send(NodeInput::Protocol(ProtocolEvent::ExecutionVoteReceived {
                    vote,
                }));
            }
        });
    }

    /// Flush accumulated execution vote verifications as a single batch.
    ///
    /// Spawns one closure on the crypto pool that uses cross-transaction BLS
    /// batch verification (~2 pairings) instead of N individual dispatches.
    fn flush_execution_vote_verifications(&mut self) {
        let items = self.execution_vote_batch.take();
        if items.is_empty() {
            return;
        }

        let event_tx = self.event_sender.clone();
        self.dispatch.spawn_crypto(move || {
            let start = std::time::Instant::now();
            for (tx_hash, verified_votes) in
                hyperscale_execution::handlers::batch_verify_and_aggregate_execution_votes(items)
            {
                let _ = event_tx.send(NodeInput::Protocol(
                    ProtocolEvent::ExecutionVotesVerifiedAndAggregated {
                        tx_hash,
                        verified_votes,
                    },
                ));
            }
            metrics::record_signature_verification_latency(
                "bls_execution_vote",
                start.elapsed().as_secs_f64(),
            );
        });
    }

    /// Flush accumulated execution certificate verifications as a single batch.
    ///
    /// Spawns one closure on the crypto pool that uses cross-certificate BLS
    /// batch verification (~2 pairings) instead of N individual dispatches.
    fn flush_execution_certificate_verifications(&mut self) {
        let items = self.execution_certificate_batch.take();
        if items.is_empty() {
            return;
        }

        let event_tx = self.event_sender.clone();
        self.dispatch.spawn_crypto(move || {
            let start = std::time::Instant::now();
            let results =
                hyperscale_execution::handlers::batch_verify_execution_certificate_signatures(
                    &items,
                );
            for ((certificate, _), valid) in items.into_iter().zip(results) {
                let _ = event_tx.send(NodeInput::Protocol(
                    ProtocolEvent::ExecutionCertificateSignatureVerified { certificate, valid },
                ));
            }
            metrics::record_signature_verification_latency(
                "bls_execution_cert",
                start.elapsed().as_secs_f64(),
            );
        });
    }

    // ─── Certificate Verification ───────────────────────────────────────

    /// Handle a received TransactionCertificate.
    ///
    /// Verifies each embedded ExecutionCertificate's BLS signature before persisting
    /// to prevent malicious peers from filling storage with invalid certificates.
    fn handle_received_certificate(&mut self, certificate: TransactionCertificate) {
        let tx_hash = certificate.transaction_hash;

        // Fast path: skip if we built this certificate locally (O(1) cache check).
        if self.cert_cache.get(&tx_hash).is_some() {
            return;
        }

        // Skip if already in verification pipeline.
        if self.pending_cert_verifications.contains_key(&tx_hash) {
            return;
        }

        // Skip if already persisted in storage.
        if self.storage.get_certificate(&tx_hash).is_some() {
            return;
        }

        // Collect shards that need verification.
        let pending_shards: HashSet<ShardGroupId> =
            certificate.shard_proofs.keys().copied().collect();

        let certificate = Arc::new(certificate);

        if pending_shards.is_empty() {
            // Empty certificate (no shard proofs) - persist directly.
            self.persist_and_notify_verified_certificate(certificate);
            return;
        }

        let now = self.state.now();

        // Track pending verification.
        self.pending_cert_verifications.insert(
            tx_hash,
            PendingCertificateVerification {
                certificate: Arc::clone(&certificate),
                pending_shards,
                failed: false,
                created_at: now,
            },
        );

        // Dispatch BLS signature verification for each shard proof.
        for (shard_id, execution_cert) in &certificate.shard_proofs {
            let committee = self.topology.committee_for_shard(*shard_id);
            let public_keys: Vec<Bls12381G1PublicKey> = committee
                .iter()
                .filter_map(|&vid| self.topology.public_key(vid))
                .collect();

            if public_keys.len() != committee.len() {
                warn!(
                    tx_hash = ?tx_hash,
                    shard = shard_id.0,
                    "Could not resolve all public keys for received certificate"
                );
                if let Some(pending) = self.pending_cert_verifications.get_mut(&tx_hash) {
                    pending.failed = true;
                    pending.pending_shards.remove(shard_id);
                    if pending.pending_shards.is_empty() {
                        self.pending_cert_verifications.remove(&tx_hash);
                    }
                }
                continue;
            }

            let es = self.event_sender.clone();
            let shard = *shard_id;
            let cert = execution_cert.clone();

            self.dispatch.spawn_crypto(move || {
                let start = std::time::Instant::now();
                let valid = hyperscale_execution::handlers::verify_execution_certificate_signature(
                    &cert,
                    &public_keys,
                );
                metrics::record_signature_verification_latency(
                    "bls_execution_cert",
                    start.elapsed().as_secs_f64(),
                );
                if !valid {
                    metrics::record_signature_verification_failure();
                }
                let _ = es.send(NodeInput::CertificateSignatureVerified {
                    tx_hash,
                    shard,
                    valid,
                });
            });
        }
    }

    /// Handle a certificate verification result from the crypto pool.
    fn handle_cert_verification_result(&mut self, tx_hash: Hash, shard: ShardGroupId, valid: bool) {
        if let Some(pending) = self.pending_cert_verifications.get_mut(&tx_hash) {
            if !valid {
                pending.failed = true;
                warn!(
                    tx_hash = ?tx_hash,
                    shard = shard.0,
                    "Certificate signature verification failed"
                );
            }
            pending.pending_shards.remove(&shard);

            if pending.pending_shards.is_empty() {
                let pending = self.pending_cert_verifications.remove(&tx_hash).unwrap();

                if !pending.failed {
                    self.persist_and_notify_verified_certificate(pending.certificate);
                }
            }
        }
    }

    /// Persist a verified certificate and notify the state machine.
    fn persist_and_notify_verified_certificate(
        &mut self,
        certificate: Arc<TransactionCertificate>,
    ) {
        let tx_hash = certificate.transaction_hash;

        // Populate cert cache.
        self.cert_cache.insert(tx_hash, Arc::clone(&certificate));

        // Persist to storage.
        self.storage.store_certificate(&certificate);

        // Feed TransactionCertificateVerified directly to state machine.
        self.feed_event(ProtocolEvent::TransactionCertificateVerified { certificate });
    }

    // ─── Batch Accumulation ─────────────────────────────────────────────

    fn accumulate_cross_shard_execution(
        &mut self,
        tx_hash: Hash,
        transaction: Arc<hyperscale_types::RoutableTransaction>,
        provisions: Vec<hyperscale_types::StateProvision>,
    ) {
        let req = CrossShardExecutionRequest {
            tx_hash,
            transaction,
            provisions,
        };
        if self.cross_shard_batch.push(req, self.state.now()) {
            self.flush_cross_shard_executions();
        }
    }

    fn accumulate_execution_vote_verification(&mut self, item: ExecutionVoteVerificationItem) {
        let weight = item.1.len();
        if self
            .execution_vote_batch
            .push_weighted(item, weight, self.state.now())
        {
            self.flush_execution_vote_verifications();
        }
    }

    fn accumulate_execution_certificate_verification(
        &mut self,
        certificate: ExecutionCertificate,
        public_keys: Vec<Bls12381G1PublicKey>,
    ) {
        if self
            .execution_certificate_batch
            .push((certificate, public_keys), self.state.now())
        {
            self.flush_execution_certificate_verifications();
        }
    }

    fn accumulate_broadcast_vote(&mut self, shard: ShardGroupId, vote: ExecutionVote) {
        if self
            .broadcast_vote_batch
            .push(shard, vote, self.state.now())
        {
            self.flush_broadcast_votes();
        }
    }

    fn accumulate_broadcast_cert(&mut self, shard: ShardGroupId, cert: Arc<ExecutionCertificate>) {
        if self
            .broadcast_cert_batch
            .push(shard, cert, self.state.now())
        {
            self.flush_broadcast_certs();
        }
    }

    // ─── Batch Flushing ─────────────────────────────────────────────────

    fn flush_broadcast_votes(&mut self) {
        for (shard, votes) in self.broadcast_vote_batch.take() {
            if !votes.is_empty() {
                let msg = hyperscale_types::exec_vote_batch_message(shard, &votes);
                let sig = self.signing_key.sign_v1(&msg);
                let batch = ExecutionVotesNotification::new(votes, self.validator_id, sig);
                self.network.notify(&self.cached_local_peers, &batch);
            }
        }
    }

    fn flush_broadcast_certs(&mut self) {
        for (shard, certs) in self.broadcast_cert_batch.take() {
            if !certs.is_empty() {
                let owned: Vec<ExecutionCertificate> =
                    certs.into_iter().map(Arc::unwrap_or_clone).collect();
                let msg = hyperscale_types::exec_cert_batch_message(shard, &owned);
                let sig = self.signing_key.sign_v1(&msg);
                let batch = ExecutionCertificatesNotification::new(owned, self.validator_id, sig);
                let recipients = self.peers_for_shard(shard);
                self.network.notify(&recipients, &batch);
            }
        }
    }

    /// Flush accumulated committed header sender-signature verifications.
    ///
    /// Spawns one closure on the crypto pool that verifies each sender's BLS
    /// signature. Valid headers are sent back as `CommittedHeaderValidated`.
    fn flush_committed_header_verifications(&mut self) {
        let items = self.committed_header_batch.take();
        if items.is_empty() {
            return;
        }

        let event_tx = self.event_sender.clone();
        self.dispatch.spawn_crypto(move || {
            for (committed_header, sender, public_key, sender_signature) in items {
                let start = std::time::Instant::now();
                let msg = hyperscale_types::committed_block_header_message(
                    committed_header.header.shard_group_id,
                    committed_header.header.height.0,
                    &committed_header.header.hash(),
                );
                let valid =
                    hyperscale_types::verify_bls12381_v1(&msg, &public_key, &sender_signature);
                metrics::record_signature_verification_latency(
                    "committed_header",
                    start.elapsed().as_secs_f64(),
                );
                if valid {
                    let _ = event_tx.send(NodeInput::CommittedHeaderValidated {
                        committed_header,
                        sender,
                    });
                } else {
                    tracing::warn!(
                        sender = sender.0,
                        height = committed_header.header.height.0,
                        "Committed header sender signature verification failed"
                    );
                }
            }
        });
    }

    // ─── Metrics ────────────────────────────────────────────────────────

    /// Collect and export metrics from the state machine.
    ///
    /// Called periodically (every ~1s) by the driving loop. Reads state from
    /// BFT, mempool, execution, livelock, sync, and fetch subsystems and
    /// emits them via the `hyperscale_metrics` facade. In production the
    /// Prometheus backend records them; in simulation the no-op backend
    /// discards them at zero cost.
    pub fn collect_metrics(&mut self) {
        // ── BFT ──
        let bft_stats = self.state.bft().stats();
        metrics::set_bft_round(bft_stats.current_round);
        metrics::set_view_changes(bft_stats.view_changes);

        // ── Speculative execution ──
        let (started, hits, late_hits, misses, invalidated) =
            self.state.execution_mut().take_speculative_metrics();
        if started > 0 {
            metrics::record_speculative_execution_started(started);
        }
        if hits > 0 {
            metrics::record_speculative_execution_cache_hit(hits);
        }
        if late_hits > 0 {
            metrics::record_speculative_execution_late_hit(late_hits);
        }
        if misses > 0 {
            metrics::record_speculative_execution_cache_miss(misses);
        }
        if invalidated > 0 {
            metrics::record_speculative_execution_invalidated(invalidated);
        }

        // ── Mempool ──
        let mempool = self.state.mempool();
        let total = mempool.len();
        let contention = mempool.lock_contention_stats();
        metrics::set_mempool_size(total);
        metrics::set_lock_contention(contention.deferred_count, contention.contention_ratio());
        let in_flight = mempool.in_flight();
        metrics::set_in_flight(in_flight);
        metrics::set_backpressure_active(mempool.at_in_flight_limit());

        // ── Sync ──
        metrics::set_sync_status(
            self.sync_protocol.blocks_behind(),
            self.sync_protocol.is_syncing(),
        );

        // ── Fetch ──
        let fetch_status = self.fetch_protocol.status();
        metrics::set_fetch_in_flight(fetch_status.in_flight_operations);

        // ── Livelock ──
        metrics::set_livelock_deferred_count(self.state.livelock().stats().pending_deferrals);

        // ── Certificate verification tracking ──
        metrics::set_pending_cert_verification_count(self.pending_cert_verifications.len());
    }

    /// Capture a snapshot of node state for external status APIs.
    pub fn status_snapshot(&self) -> NodeStatusSnapshot {
        let (_, state_version, state_root) = self.state.last_committed_state();
        let mempool = self.state.mempool();
        let contention = mempool.lock_contention_stats();

        NodeStatusSnapshot {
            committed_height: self.state.bft().committed_height(),
            view: self.state.bft().view(),
            state_version,
            state_root,
            sync: self.sync_protocol.status(),
            mempool_pending: contention.pending_count as usize,
            mempool_committed: contention.committed_count as usize,
            mempool_executed: contention.executed_count as usize,
            mempool_total: mempool.len(),
            mempool_deferred: contention.deferred_count as usize,
            accepting_rpc_transactions: !mempool.at_in_flight_hard_limit(),
            at_pending_limit: mempool.at_pending_limit(),
        }
    }

    /// Flush ALL pending batches immediately, regardless of deadlines.
    ///
    /// Called during shutdown or when immediate delivery is needed.
    pub fn flush_all_batches(&mut self) {
        self.flush_validation_batch();
        self.flush_cross_shard_executions();
        self.flush_execution_vote_verifications();
        self.flush_execution_certificate_verifications();
        self.flush_broadcast_votes();
        self.flush_broadcast_certs();
        self.flush_committed_header_verifications();
    }
}
